server:
  port: 8761
spring:
  application:
    name: service-registry
billing:
  app: This is billing App Service Discovery default service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false